const ITER=600000, MIN=12, SESSION_MS=8*60*60*1000, VERIFY_MS=24*60*60*1000, RESET_MS=30*60*1000;
const enc=v=>new TextEncoder().encode(String(v));
function b64u(bytes){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");}
function unb64(v){const s=atob(v.replace(/-/g,"+").replace(/_/g,"/")+"===".slice((v.length+3)%4));return Uint8Array.from(s,c=>c.charCodeAt(0));}
function token(n=32){const b=new Uint8Array(n);crypto.getRandomValues(b);return b64u(b);}
async function sha(v){return b64u(new Uint8Array(await crypto.subtle.digest("SHA-256",enc(v))));}
async function derive(password,salt,iterations=ITER){const k=await crypto.subtle.importKey("raw",enc(password),"PBKDF2",false,["deriveBits"]);return new Uint8Array(await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt,iterations},k,256));}
async function hashPassword(password){if(typeof password!=="string"||password.length<MIN||password.length>1024)throw new Error("invalid password");const salt=new Uint8Array(16);crypto.getRandomValues(salt);return "pbkdf2-sha256$"+ITER+"$"+b64u(salt)+"$"+b64u(await derive(password,salt));}
async function verifyPassword(password,stored){const p=String(stored||"").split("$");if(p.length!==4||p[0]!=="pbkdf2-sha256")return false;const it=Number(p[1]);if(!Number.isInteger(it)||it<100000||it>2000000)return false;let salt,expected;try{salt=unb64(p[2]);expected=unb64(p[3]);}catch{return false;}const actual=await derive(password,salt,it);if(actual.length!==expected.length)return false;let d=0;for(let i=0;i<actual.length;i++)d|=actual[i]^expected[i];return d===0;}
function normalizeEmail(v){return String(v||"").trim().toLowerCase();}
function validEmail(v){return v.length>=3&&v.length<=320&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);}
function json(body,status=200,extra={}){return Response.json(body,{status,headers:{"Cache-Control":"no-store",...extra}});}
function cookies(request){const out={};for(const part of (request.headers.get("cookie")||"").split(";")){const i=part.indexOf("=");if(i>0)out[part.slice(0,i).trim()]=decodeURIComponent(part.slice(i+1).trim());}return out;}
function sessionCookie(v,maxAge){return "__Host-alex_session="+encodeURIComponent(v)+"; Max-Age="+maxAge+"; Path=/; Secure; HttpOnly; SameSite=Strict";}
function clearSession(){return sessionCookie("",0);}
function csrfCookie(v,maxAge=28800){return "alex_csrf="+encodeURIComponent(v)+"; Max-Age="+maxAge+"; Path=/; Secure; SameSite=Strict";}
function originOK(req){const o=req.headers.get("Origin");return !o||o===new URL(req.url).origin;}
async function csrfOK(req){if(!originOK(req))return false;const c=cookies(req).alex_csrf||"",h=req.headers.get("x-csrf-token")||"";if(!c||!h||c.length!==h.length)return false;let d=0;for(let i=0;i<c.length;i++)d|=c.charCodeAt(i)^h.charCodeAt(i);return d===0;}
async function audit(env,userId,type,success=true,meta={}){await env.CENTRAL_DB.prepare("INSERT INTO security_events (event_id,user_id,event_type,success,metadata_json,created_at) VALUES (?,?,?,?,?,?)").bind(crypto.randomUUID(),userId||null,type,success?1:0,JSON.stringify(meta),new Date().toISOString()).run();}
async function createSession(env,userId){const id=crypto.randomUUID(),v=token(),csrf=token(),now=new Date(),exp=new Date(now.getTime()+SESSION_MS);await env.CENTRAL_DB.prepare("INSERT INTO user_sessions (session_id,user_id,verifier_hash,csrf_token_hash,created_at,expires_at,last_seen_at) VALUES (?,?,?,?,?,?,?)").bind(id,userId,await sha(v),await sha(csrf),now.toISOString(),exp.toISOString(),now.toISOString()).run();return {cookie:id+"."+v,csrf,expires:exp.toISOString()};}
async function currentSession(env,req){const raw=cookies(req)["__Host-alex_session"]||"",i=raw.indexOf(".");if(i<1)return null;const id=raw.slice(0,i),v=raw.slice(i+1);const r=await env.CENTRAL_DB.prepare("SELECT s.session_id,s.user_id,s.verifier_hash,s.expires_at,s.revoked_at,u.email_display,u.email_verified_at,u.status FROM user_sessions s JOIN users u ON u.user_id=s.user_id WHERE s.session_id=? LIMIT 1").bind(id).first();if(!r||r.revoked_at||r.status!=="active"||new Date(r.expires_at).getTime()<=Date.now()||await sha(v)!==r.verifier_hash)return null;return r;}
async function requireSession(env,req){const s=await currentSession(env,req);return s?{session:s}:{response:json({ok:false,error:"authentication required"},401)};}
async function body(req){try{return await req.json();}catch{return null;}}
async function sendEmail(env,m){
  if(env.EMAIL){await env.EMAIL.send(m);return true;}
  if(!env.RESEND_API_KEY||!env.AUTH_EMAIL_FROM)return false;
  const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{"authorization":"Bearer "+env.RESEND_API_KEY,"content-type":"application/json"},body:JSON.stringify({from:m.from||env.AUTH_EMAIL_FROM,to:Array.isArray(m.to)?m.to:[m.to],subject:m.subject,text:m.text,html:m.html})});
  if(!response.ok){const detail=await response.text().catch(()=> "");throw new Error("transactional email delivery failed ("+response.status+"): "+detail.slice(0,200));}
  return true;
}
async function issueVerify(env,user){const t=token(),h=await sha(t),exp=new Date(Date.now()+VERIFY_MS).toISOString();await env.CENTRAL_DB.prepare("INSERT INTO email_verification_tokens (token_hash,user_id,expires_at,created_at) VALUES (?,?,?,?)").bind(h,user.user_id,exp,new Date().toISOString()).run();const url=(env.AUTH_BASE_URL||"")+"/api/auth/verify-email?token="+encodeURIComponent(t);return sendEmail(env,{to:user.email_display,from:env.AUTH_EMAIL_FROM,subject:"Verify your ALEX-MIND account",text:"Verify your ALEX-MIND account: "+url,html:"<p>Verify your ALEX-MIND account.</p><p><a href=\""+url+"\">Verify email</a></p>"});}
async function issueReset(env,user){const t=token(),h=await sha(t),exp=new Date(Date.now()+RESET_MS).toISOString();await env.CENTRAL_DB.prepare("INSERT INTO password_reset_tokens (token_hash,user_id,expires_at,created_at) VALUES (?,?,?,?)").bind(h,user.user_id,exp,new Date().toISOString()).run();const url=(env.AUTH_BASE_URL||"")+"/reset-password?token="+encodeURIComponent(t);return sendEmail(env,{to:user.email_display,from:env.AUTH_EMAIL_FROM,subject:"Reset your ALEX-MIND password",text:"Reset your ALEX-MIND password: "+url,html:"<p>Reset your ALEX-MIND password.</p><p><a href=\""+url+"\">Reset password</a></p>"});}
async function authRoutes(req,env){const u=new URL(req.url),p=u.pathname;if(!p.startsWith("/api/auth/"))return null;
if(p==="/api/auth/csrf"&&req.method==="GET"){const t=token();return new Response(JSON.stringify({ok:true,csrf_token:t}),{headers:{"content-type":"application/json","cache-control":"no-store","Set-Cookie":csrfCookie(t)}});}
if(req.method==="POST"&&!originOK(req))return json({ok:false,error:"origin rejected"},403);
if(req.method==="POST"&&p!=="/api/auth/reset-password"&&p!=="/api/auth/forgot-password"&&p!=="/api/auth/resend-verification"&&!await csrfOK(req))return json({ok:false,error:"csrf rejected"},403);
if(p==="/api/auth/signup"&&req.method==="POST"){const b=await body(req),email=normalizeEmail(b?.email),password=b?.password;if(!validEmail(email)||typeof password!=="string"||password.length<MIN||password.length>1024)return json({ok:false,error:"invalid signup data"},400);if(await env.CENTRAL_DB.prepare("SELECT user_id FROM users WHERE email_normalized=? LIMIT 1").bind(email).first())return json({ok:false,error:"account already exists"},409);if(!env.EMAIL||!env.AUTH_EMAIL_FROM||!env.AUTH_BASE_URL)return json({ok:false,error:"account email delivery is not configured"},503);const id="usr-"+crypto.randomUUID(),now=new Date().toISOString(),ph=await hashPassword(password);await env.CENTRAL_DB.batch([env.CENTRAL_DB.prepare("INSERT INTO users (user_id,email_normalized,email_display,status,created_at,updated_at) VALUES (?,?,?,?,?,?)").bind(id,email,email,"pending",now,now),env.CENTRAL_DB.prepare("INSERT INTO user_credentials (user_id,password_hash,password_changed_at,created_at,updated_at) VALUES (?,?,?,?,?)").bind(id,ph,now,now,now)]);try{if(!await issueVerify(env,{user_id:id,email_display:email}))throw new Error("email");}catch{await env.CENTRAL_DB.batch([env.CENTRAL_DB.prepare("DELETE FROM user_credentials WHERE user_id=?").bind(id),env.CENTRAL_DB.prepare("DELETE FROM users WHERE user_id=?").bind(id)]);return json({ok:false,error:"verification email could not be sent"},503);}await audit(env,id,"signup");return json({ok:true,status:"VERIFICATION_REQUIRED"},201);}
if(p==="/api/auth/verify-email"&&req.method==="GET"){const h=await sha(u.searchParams.get("token")||""),r=await env.CENTRAL_DB.prepare("SELECT token_hash,user_id,expires_at,used_at FROM email_verification_tokens WHERE token_hash=? LIMIT 1").bind(h).first();if(!r||r.used_at||new Date(r.expires_at).getTime()<=Date.now())return json({ok:false,error:"invalid or expired verification token"},400);const now=new Date().toISOString();await env.CENTRAL_DB.batch([env.CENTRAL_DB.prepare("UPDATE email_verification_tokens SET used_at=? WHERE token_hash=?").bind(now,h),env.CENTRAL_DB.prepare("UPDATE users SET status='active',email_verified_at=?,updated_at=? WHERE user_id=?").bind(now,now,r.user_id)]);await audit(env,r.user_id,"email_verified");return json({ok:true,status:"VERIFIED"});}
if(p==="/api/auth/login"&&req.method==="POST"){const b=await body(req),email=normalizeEmail(b?.email),password=b?.password,generic=()=>json({ok:false,error:"invalid email or password"},401),r=await env.CENTRAL_DB.prepare("SELECT u.user_id,u.email_display,u.status,u.email_verified_at,c.password_hash,c.failed_attempts,c.locked_until FROM users u JOIN user_credentials c ON c.user_id=u.user_id WHERE u.email_normalized=? LIMIT 1").bind(email).first();if(!r||typeof password!=="string")return generic();if(r.locked_until&&new Date(r.locked_until).getTime()>Date.now())return generic();if(!await verifyPassword(password,r.password_hash)){const n=Number(r.failed_attempts||0)+1,lock=n>=8?new Date(Date.now()+15*60*1000).toISOString():null;await env.CENTRAL_DB.prepare("UPDATE user_credentials SET failed_attempts=?,locked_until=?,updated_at=? WHERE user_id=?").bind(n,lock,new Date().toISOString(),r.user_id).run();await audit(env,r.user_id,"login",false);return generic();}if(r.status!=="active"||!r.email_verified_at)return json({ok:false,error:"email verification required"},403);const s=await createSession(env,r.user_id),now=new Date().toISOString();await env.CENTRAL_DB.batch([env.CENTRAL_DB.prepare("UPDATE user_credentials SET failed_attempts=0,locked_until=NULL,updated_at=? WHERE user_id=?").bind(now,r.user_id),env.CENTRAL_DB.prepare("UPDATE users SET last_login_at=?,updated_at=? WHERE user_id=?").bind(now,now,r.user_id)]);await audit(env,r.user_id,"login");return new Response(JSON.stringify({ok:true,user:{user_id:r.user_id,email:r.email_display,email_verified:true},expires_at:s.expires}),{headers:{"content-type":"application/json","cache-control":"no-store","Set-Cookie":sessionCookie(s.cookie,Math.floor(SESSION_MS/1000))}});}
if(p==="/api/auth/me"&&req.method==="GET"){const r=await requireSession(env,req);if(r.response)return r.response;return json({ok:true,user:{user_id:r.session.user_id,email:r.session.email_display,email_verified:!!r.session.email_verified_at}});}
if(p==="/api/auth/logout"&&req.method==="POST"){const r=await requireSession(env,req);if(r.response)return r.response;if(!await csrfOK(req))return json({ok:false,error:"csrf rejected"},403);await env.CENTRAL_DB.prepare("UPDATE user_sessions SET revoked_at=? WHERE session_id=?").bind(new Date().toISOString(),r.session.session_id).run();await audit(env,r.session.user_id,"logout");return new Response(JSON.stringify({ok:true}),{headers:{"content-type":"application/json","cache-control":"no-store","Set-Cookie":clearSession()}});}
if(p==="/api/auth/forgot-password"&&req.method==="POST"){const b=await body(req),email=normalizeEmail(b?.email),r=validEmail(email)?await env.CENTRAL_DB.prepare("SELECT user_id,email_display,status FROM users WHERE email_normalized=? LIMIT 1").bind(email).first():null;if(r&&r.status!=="disabled"&&env.EMAIL&&env.AUTH_EMAIL_FROM&&env.AUTH_BASE_URL)await issueReset(env,r);return json({ok:true,message:"If that account exists, a password reset email will be sent."});}
if(p==="/api/auth/reset-password"&&req.method==="POST"){const b=await body(req),t=String(b?.token||""),password=b?.password;if(!t||typeof password!=="string"||password.length<MIN||password.length>1024)return json({ok:false,error:"invalid reset data"},400);const h=await sha(t),r=await env.CENTRAL_DB.prepare("SELECT token_hash,user_id,expires_at,used_at FROM password_reset_tokens WHERE token_hash=? LIMIT 1").bind(h).first();if(!r||r.used_at||new Date(r.expires_at).getTime()<=Date.now())return json({ok:false,error:"invalid or expired reset token"},400);const now=new Date().toISOString(),ph=await hashPassword(password);await env.CENTRAL_DB.batch([env.CENTRAL_DB.prepare("UPDATE user_credentials SET password_hash=?,password_changed_at=?,failed_attempts=0,locked_until=NULL,updated_at=? WHERE user_id=?").bind(ph,now,now,r.user_id),env.CENTRAL_DB.prepare("UPDATE password_reset_tokens SET used_at=? WHERE token_hash=?").bind(now,h),env.CENTRAL_DB.prepare("UPDATE user_sessions SET revoked_at=? WHERE user_id=? AND revoked_at IS NULL").bind(now,r.user_id)]);await audit(env,r.user_id,"password_reset_completed");return json({ok:true,message:"Password reset. Please log in again."});}
if(p==="/api/auth/resend-verification"&&req.method==="POST"){const b=await body(req),email=normalizeEmail(b?.email),r=validEmail(email)?await env.CENTRAL_DB.prepare("SELECT user_id,email_display,status,email_verified_at FROM users WHERE email_normalized=? LIMIT 1").bind(email).first():null;if(r&&r.status!=="disabled"&&!r.email_verified_at&&env.EMAIL&&env.AUTH_EMAIL_FROM&&env.AUTH_BASE_URL)await issueVerify(env,r);return json({ok:true,message:"If the account is eligible, a verification email will be sent."});}
return json({ok:false,error:"not found"},404);}
export {authRoutes,hashPassword,verifyPassword,normalizeEmail,requireSession};